import { isDarkMode, genHexColor, isHexColor } from '../src/browser'
import { mockMatchMedia, clear } from '../__mocks__/matchMedia'
describe('browser', () => {

  describe('isDarkMode', () => {
    test('The disordered array should be inconsistent with the original array', () => {
      mockMatchMedia(true)
      expect(isDarkMode()).toBe(true)
      clear()
    })

    test('The result should be false for bright themes', () => {
      mockMatchMedia(false)
      expect(isDarkMode()).toBe(false)
      clear()
    })
  })

  describe('genHexColor', () => {
    test('The colour generated by the genHexColor method should be true', () => {
      expect(isHexColor(genHexColor())).toBe(true)
    })
  })

  describe('isHexColor', () => {
    test('The colour generated by the genHexColor method should be true', () => {
      expect(isHexColor(genHexColor())).toBe(true)
    })
    test('The normal string should be false', () => {
      expect(isHexColor('123')).toBe(false)
    })
  })
})
