
name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      
      - name: Deploy:Docs
        run: pnpm run docs
      - uses: github-actions-x/commit@v2.8
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          push-branch: gh-pages
          commit-message: deploy
